apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-az
  name: letsencrypt-az
spec:
 acme:
  email: mathur.ap@northeastern.edu
  privateKeySecretRef:
    name: letsencrypt-privatekey
  server: https://acme-v02.api.letsencrypt.org/directory
  solvers:
  - http01:
      ingress:
        class: nginx
